blank_issues_enabled: false
contact_links:
  - name: â“ Questions, Help, and Advice
    url: https://github.com/discontinuedlabs/citeease/discussions
    about: For general support, please refer to our discussion board for questions, help, or advice.

  - name: ğŸ“§ Email Support
    url: mailto:discontinuedlabs@gmail.com
    about: If you need further assistance, feel free to contact us via email.
